In [1]:
# importing libraries  
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd

In [3]:
#importing datasets  
data_set= pd.read_csv('dataPreprocesing.csv')
data_set.head()

Country    Age   Salary Purchese 
0    India  38.0  68000.0        No
1   France  43.0  45000.0       Yes
2  Germany  30.0  54000.0        No
3      USA  36.0      NaN       Yes
4    Ghana   NaN  60000.0       Yes

In [4]:
#Extracting Independent Variable  
x= data_set.iloc[:, :-1].values

In [5]:
print(x)

[['India' 38.0 68000.0]
 ['France' 43.0 45000.0]
 ['Germany' 30.0 54000.0]
 ['USA' 36.0 nan]
 ['Ghana' nan 60000.0]
 ['India' 80.0 nan]
 ['France' nan 30000.0]
 ['USA' 14.0 25000.0]]


In [6]:
#Extracting Dependent variable  
y= data_set.iloc[:, 3].values
print(y)

['No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No']


In [9]:
#handling missing data(Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer  
imputer= SimpleImputer(missing_values =nm.nan, strategy='mean') 

In [10]:
#Fitting imputer object to the independent varibles x.   
imputerimputer= imputer.fit(x[:, 1:3]) 

In [11]:
#Replacing missing data with the calculated mean value  
x[:, 1:3]= imputer.transform(x[:, 1:3]) 

In [12]:
#for Country Variable  
from sklearn.preprocessing import LabelEncoder, OneHotEncoder  
label_encoder_x= LabelEncoder()  
x[:, 0]= label_encoder_x.fit_transform(x[:, 0]) 

In [14]:
#Encoding for dummy variables  
onehot_encoder= OneHotEncoder()    
x= onehot_encoder.fit_transform(x).toarray()

In [15]:
print(x)

[[0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [16]:
#encoding for purchased variable  
labelencoder_y= LabelEncoder()  
y= labelencoder_y.fit_transform(y) 

In [17]:
print(y)

[0 1 0 1 1 0 1 0]


In [18]:
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0) 

In [19]:
print(x_train)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [20]:
#Feature Scaling of datasets  
from sklearn.preprocessing import StandardScaler  
st_x= StandardScaler()  
x_train= st_x.fit_transform(x_train)  
x_test= st_x.transform(x_test)